<?php

namespace App\Services\Cash;

use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;
use Symfony\Component\HttpKernel\Exception\HttpException;

class CashLedgerService
{
    public function requireOpenSessionForUpdate(int $tenantId): object
    {
        if ($tenantId <= 0) {
            throw new HttpException(403, 'Tenant context is required.');
        }

        $session = DB::table('cash_sessions')
            ->where('tenant_id', $tenantId)
            ->where('status', 'open')
            ->lockForUpdate()
            ->first(['id', 'tenant_id', 'opening_amount', 'opened_at']);

        if ($session === null) {
            throw new HttpException(422, 'Cash operation requires an open cash session.');
        }

        return $session;
    }

    public function recordSaleCashIn(
        int $tenantId,
        int $cashSessionId,
        int $saleId,
        int $userId,
        float $amount,
        string $reference,
    ): ?int {
        return $this->insertEntry(
            $tenantId,
            $cashSessionId,
            'sale',
            $saleId,
            'sale_cash_in',
            'in',
            $amount,
            $reference,
            'Cash sale registered',
            $userId,
        );
    }

    public function recordReceivableCashIn(
        int $tenantId,
        int $cashSessionId,
        int $paymentId,
        int $userId,
        float $amount,
        string $reference,
    ): ?int {
        return $this->insertEntry(
            $tenantId,
            $cashSessionId,
            'sale_receivable_payment',
            $paymentId,
            'receivable_cash_in',
            'in',
            $amount,
            $reference,
            'Receivable cash payment registered',
            $userId,
        );
    }

    public function recordSaleCashReversal(
        int $tenantId,
        int $cashSessionId,
        int $saleId,
        int $userId,
        float $amount,
        string $reference,
    ): ?int {
        return $this->insertEntry(
            $tenantId,
            $cashSessionId,
            'sale',
            $saleId,
            'sale_cash_reversal',
            'out',
            $amount,
            $reference,
            'Cash sale cancellation registered',
            $userId,
        );
    }

    public function recordManualMovement(
        int $tenantId,
        int $cashSessionId,
        int $cashMovementId,
        int $userId,
        string $type,
        float $amount,
        string $reference,
        ?string $notes = null,
    ): ?int {
        $direction = $type === 'manual_in' ? 'in' : 'out';

        return $this->insertEntry(
            $tenantId,
            $cashSessionId,
            'cash_movement',
            $cashMovementId,
            $type,
            $direction,
            $amount,
            $reference,
            $notes,
            $userId,
        );
    }

    public function recordCreditNoteRefund(
        int $tenantId,
        int $cashSessionId,
        int $refundId,
        int $userId,
        float $amount,
        string $reference,
    ): ?int {
        return $this->insertEntry(
            $tenantId,
            $cashSessionId,
            'sale_refund',
            $refundId,
            'credit_note_refund',
            'out',
            $amount,
            $reference,
            'Cash refund generated by credit note',
            $userId,
        );
    }

    private function insertEntry(
        int $tenantId,
        int $cashSessionId,
        string $sourceType,
        int $sourceId,
        string $entryType,
        string $direction,
        float $amount,
        string $reference,
        ?string $notes,
        int $userId,
    ): ?int {
        if ($amount <= 0) {
            throw new HttpException(422, 'Cash ledger amount must be valid.');
        }

        if (! in_array($direction, ['in', 'out'], true)) {
            throw new HttpException(422, 'Cash ledger direction is invalid.');
        }

        try {
            return (int) DB::table('cash_session_ledger_entries')->insertGetId([
                'tenant_id' => $tenantId,
                'cash_session_id' => $cashSessionId,
                'source_type' => $sourceType,
                'source_id' => $sourceId,
                'entry_type' => $entryType,
                'direction' => $direction,
                'amount' => round($amount, 2),
                'reference' => $reference,
                'notes' => $notes,
                'created_by_user_id' => $userId,
                'occurred_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        } catch (QueryException $exception) {
            if ($this->isDuplicateSource($exception)) {
                return DB::table('cash_session_ledger_entries')
                    ->where('source_type', $sourceType)
                    ->where('source_id', $sourceId)
                    ->where('entry_type', $entryType)
                    ->value('id');
            }

            throw $exception;
        }
    }

    private function isDuplicateSource(QueryException $exception): bool
    {
        $message = strtolower($exception->getMessage());
        $previous = strtolower($exception->getPrevious()?->getMessage() ?? '');

        foreach ([
            'cash_ledger_source_unique',
            'cash_session_ledger_entries.source_type',
            'unique constraint failed',
            'duplicate entry',
        ] as $needle) {
            if (str_contains($message, $needle) || ($previous !== '' && str_contains($previous, $needle))) {
                return true;
            }
        }

        return false;
    }
}
